"""empty message

Revision ID: 50142c1176f5
Revises: 5104359dbebe
Create Date: 2022-12-02 15:02:00.355758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50142c1176f5'
down_revision = '5104359dbebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
